name: jacoco-coverage-reusable
permissions:
  contents: read
  id-token: write
  actions: read
  security-events: write

on:
  workflow_dispatch:
    inputs:
      LZ_ENVIRONMENT: 
        description: "Environment to apply changes"
        default: "dev"
        type: choice
        required: true
        options:
          - "dev"
          - "uat"
          - "prd"

jobs:
  execute-jacaco-coverage:
    uses: nigamshashankblueberry/blueberry-reusable-workflows/.github/workflows/jacoco-coverage.yaml@devops
    secrets: inherit
    with:
     environment: ${{ github.event.inputs.LZ_ENVIRONMENT}}
    
